version: '2.1'

services:
  what-is-my-ip:
    image: what-is-my-ip
    build: .
    environment:
      NODE_ENV: development
    ports:
      - 9001:9001
      - 9229:9229
    command: node --inspect=0.0.0.0:9229 server.js